# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df59bae745413d5863de26684c2a8c795d2e5dc706bc63ddc684779113c6eedbbaa8fd973e38ef7b2c708c34fccba2d40f7de8eee8d43ab2dafc79d031feb45d

test:
  secret_key_base: 4fa8cb22f0afc52404e487cfe3f466b147835d1a2241db1f849c5f6b725158b7be0dfa21812b6448a6d9d0bb3cb3cd87b9cb4dbba1dd868e3daf93eda4a69da5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
